insert into country values ( 4,'Afghanistan');
insert into country values ( 5,'Albania');
insert into country values ( 6,'Algeria');
insert into country values ( 7,'Andorra');
insert into country values ( 8,'Angola');
insert into country values ( 10,'Antigua and Barbuda');
insert into country values ( 11,'Argentina');
insert into country values ( 12,'Armenia');
insert into country values ( 14,'Australia');
insert into country values ( 15,'Austria');
insert into country values ( 16,'Azerbaijan');
insert into country values ( 17,'Bahamas');
insert into country values ( 18,'Bahrain');
insert into country values ( 19,'Bangladesh');
insert into country values ( 20,'Barbados');
insert into country values ( 21,'Belgium');
insert into country values ( 22,'Belize');
insert into country values ( 23,'Benin');
insert into country values ( 25,'Bhutan');
insert into country values ( 26,'Bolivia');
insert into country values ( 28,'Bosnia-Herzegovina');
insert into country values ( 29,'Botswana');
insert into country values ( 30,'Brazil');
insert into country values ( 31,'Brunei');
insert into country values ( 32,'Bulgaria');
insert into country values ( 33,'Burkina Faso');
insert into country values ( 34,'Burundi');
insert into country values ( 35,'Belarus');
insert into country values ( 36,'Cambodia');
insert into country values ( 37,'Cameroon');
insert into country values ( 38,'Canada');
insert into country values ( 41,'Central African Republic');
insert into country values ( 42,'Chad');
insert into country values ( 43,'Chile');
insert into country values ( 44,'China');
insert into country values ( 45,'Colombia');
insert into country values ( 46,'Comoros');
insert into country values ( 47,'Republic of the Congo');
insert into country values ( 49,'Costa Rica');
insert into country values ( 50,'Croatia');
insert into country values ( 51,'Cuba');
insert into country values ( 53,'Cyprus');
insert into country values ( 54,'Czech Republic');
insert into country values ( 55,'Denmark');
insert into country values ( 56,'Djibouti');
insert into country values ( 57,'Dominica');
insert into country values ( 58,'Dominican Republic');
insert into country values ( 59,'Ecuador');
insert into country values ( 60,'Egypt');
insert into country values ( 61,'El Salvador');
insert into country values ( 62,'Equatorial Guinea');
insert into country values ( 63,'Eritrea');
insert into country values ( 64,'Estonia');
insert into country values ( 65,'Ethiopia');
insert into country values ( 66,'Falkland Islands');
insert into country values ( 67,'Fiji');
insert into country values ( 68,'Finland');
insert into country values ( 69,'France');
insert into country values ( 70,'French Guiana');
insert into country values ( 71,'French Polynesia');
insert into country values ( 72,'Gabon');
insert into country values ( 73,'Gambia');
insert into country values ( 74,'Georgia');
insert into country values ( 75,'Germany');
insert into country values ( 76,'Ghana');
insert into country values ( 78,'Greece');
insert into country values ( 80,'Grenada');
insert into country values ( 81,'Guadeloupe');
insert into country values ( 83,'Guatemala');
insert into country values ( 84,'Guinea');
insert into country values ( 85,'Guinea-Bissau');
insert into country values ( 86,'Guyana');
insert into country values ( 87,'Haiti');
insert into country values ( 88,'Honduras');
insert into country values ( 89,'Hong Kong');
insert into country values ( 90,'Hungary');
insert into country values ( 91,'Iceland');
insert into country values ( 92,'India');
insert into country values ( 93,'Indonesia');
insert into country values ( 94,'Iran');
insert into country values ( 95,'Iraq');
insert into country values ( 96,'Ireland');
insert into country values ( 97,'Israel');
insert into country values ( 98,'Italy');
insert into country values ( 99,'Ivory Coast');
insert into country values ( 100,'Jamaica');
insert into country values ( 101,'Japan');
insert into country values ( 102,'Jordan');
insert into country values ( 103,'Kazakhstan');
insert into country values ( 104,'Kenya');
insert into country values ( 106,'Kuwait');
insert into country values ( 107,'Kyrgyzstan');
insert into country values ( 108,'Laos');
insert into country values ( 109,'Latvia');
insert into country values ( 110,'Lebanon');
insert into country values ( 111,'Lesotho');
insert into country values ( 112,'Liberia');
insert into country values ( 113,'Libya');
insert into country values ( 115,'Lithuania');
insert into country values ( 116,'Luxembourg');
insert into country values ( 117,'Macau');
insert into country values ( 118,'Macedonia');
insert into country values ( 119,'Madagascar');
insert into country values ( 120,'Malawi');
insert into country values ( 121,'Malaysia');
insert into country values ( 122,'Maldives');
insert into country values ( 123,'Mali');
insert into country values ( 124,'Malta');
insert into country values ( 127,'Martinique');
insert into country values ( 128,'Mauritania');
insert into country values ( 129,'Mauritius');
insert into country values ( 130,'Mexico');
insert into country values ( 132,'Moldova');
insert into country values ( 136,'Morocco');
insert into country values ( 137,'Mozambique');
insert into country values ( 138,'Myanmar');
insert into country values ( 139,'Namibia');
insert into country values ( 141,'Nepal');
insert into country values ( 142,'Netherlands');
insert into country values ( 143,'New Caledonia');
insert into country values ( 144,'New Zealand');
insert into country values ( 145,'Nicaragua');
insert into country values ( 146,'Niger');
insert into country values ( 147,'Nigeria');
insert into country values ( 149,'North Korea');
insert into country values ( 151,'Norway');
insert into country values ( 153,'Pakistan');
insert into country values ( 155,'West Bank and Gaza Strip');
insert into country values ( 156,'Panama');
insert into country values ( 157,'Papua New Guinea');
insert into country values ( 158,'Paraguay');
insert into country values ( 159,'Peru');
insert into country values ( 160,'Philippines');
insert into country values ( 161,'Poland');
insert into country values ( 162,'Portugal');
insert into country values ( 164,'Qatar');
insert into country values ( 166,'Romania');
insert into country values ( 167,'Russia');
insert into country values ( 168,'Rwanda');
insert into country values ( 173,'Saudi Arabia');
insert into country values ( 174,'Senegal');
insert into country values ( 175,'Serbia-Montenegro');
insert into country values ( 176,'Seychelles');
insert into country values ( 177,'Sierra Leone');
insert into country values ( 178,'Singapore');
insert into country values ( 179,'Slovak Republic');
insert into country values ( 180,'Slovenia');
insert into country values ( 181,'Solomon Islands');
insert into country values ( 182,'Somalia');
insert into country values ( 183,'South Africa');
insert into country values ( 184,'South Korea');
insert into country values ( 185,'Spain');
insert into country values ( 186,'Sri Lanka');
insert into country values ( 189,'St. Kitts and Nevis');
insert into country values ( 190,'St. Lucia');
insert into country values ( 195,'Sudan');
insert into country values ( 196,'Suriname');
insert into country values ( 197,'Swaziland');
insert into country values ( 198,'Sweden');
insert into country values ( 199,'Switzerland');
insert into country values ( 200,'Syria');
insert into country values ( 201,'Taiwan');
insert into country values ( 202,'Tajikistan');
insert into country values ( 203,'Tanzania');
insert into country values ( 204,'Togo');
insert into country values ( 205,'Thailand');
insert into country values ( 207,'Trinidad and Tobago');
insert into country values ( 208,'Tunisia');
insert into country values ( 209,'Turkey');
insert into country values ( 210,'Turkmenistan');
insert into country values ( 213,'Uganda');
insert into country values ( 214,'Ukraine');
insert into country values ( 215,'United Arab Emirates');
insert into country values ( 217,'United States');
insert into country values ( 218,'Uruguay');
insert into country values ( 219,'Uzbekistan');
insert into country values ( 220,'Vanuatu');
insert into country values ( 221,'Vatican City');
insert into country values ( 222,'Venezuela');
insert into country values ( 223,'Vietnam');
insert into country values ( 226,'Wallis and Futuna');
insert into country values ( 228,'Yemen');
insert into country values ( 229,'Democratic Republic of the Congo');
insert into country values ( 230,'Zambia');
insert into country values ( 231,'Zimbabwe');
insert into country values ( 235,'Yugoslavia');
insert into country values ( 236,'Czechoslovakia');
insert into country values ( 347,'East Timor');
insert into country values ( 349,'Western Sahara');
insert into country values ( 359,'Soviet Union');
insert into country values ( 362,'West Germany (FRG)');
insert into country values ( 377,'North Yemen');
insert into country values ( 403,'Rhodesia');
insert into country values ( 406,'South Yemen');
insert into country values ( 422,'International');
insert into country values ( 428,'South Vietnam');
insert into country values ( 499,'East Germany (GDR)');
insert into country values ( 532,'New Hebrides');
insert into country values ( 603,'United Kingdom');
insert into country values ( 604,'Zaire');
insert into country values ( 605,'Peoples Republic of the Congo');
insert into country values ( 1001,'Serbia');
insert into country values ( 1002,'Montenegro');
insert into country values ( 1003,'Kosovo');
insert into country values ( 1004,'South Sudan');
