insert into target_type values(1,'Business');
insert into target_type values(2,'Government (General)');
insert into target_type values(3,'Police');
insert into target_type values(4,'Military');
insert into target_type values(5,'Abortion Related');
insert into target_type values(6,'Airports & Aircraft');
insert into target_type values(7,'Government (Diplomatic)');
insert into target_type values(8,'Educational Institution');
insert into target_type values(9,'Food or Water Supply');
insert into target_type values(10,'Journalists & Media');
insert into target_type values(11,'Maritime');
insert into target_type values(12,'NGO');
insert into target_type values(13,'Other');
insert into target_type values(14,'Private Citizens & Property');
insert into target_type values(15,'Religious Figures/Institutions');
insert into target_type values(16,'Telecommunication');
insert into target_type values(17,'Terrorists/Non-State Militia');
insert into target_type values(18,'Tourists');
insert into target_type values(19,'Transportation');
insert into target_type values(20,'Unknown');
insert into target_type values(21,'Utilities');
insert into target_type values(22,'Violent Political Party');
