insert into target_subtype values (1,'Gas/Oil/Electric',1);
insert into target_subtype values (2,'Restaurant/Bar/Café',1);
insert into target_subtype values (3,'Bank/Commerce',1);
insert into target_subtype values (4,'Multinational Corporation',1);
insert into target_subtype values (5,'Industrial/Textiles/Factory',1);
insert into target_subtype values (6,'Medical/Pharmaceutical',1);
insert into target_subtype values (7,'Retail/Grocery/Bakery',1);
insert into target_subtype values (8,'Hotel/Resort',1);
insert into target_subtype values (9,'Farm/Ranch',1);
insert into target_subtype values (10,'Mining',1);
insert into target_subtype values (11,'Entertainment/Cultural/Stadium/Casino',1);
insert into target_subtype values (12,'Construction',1);
insert into target_subtype values (13,'Private Security Company/Firm',1);
insert into target_subtype values (14,'Judge/Attorney/Court',2);
insert into target_subtype values (15,'Politician or Political Party Movement/Meeting/Rally',2);
insert into target_subtype values (16,'Royalty',2);
insert into target_subtype values (17,'Head of State',2);
insert into target_subtype values (18,'Government Personnel (excluding police, military)',2);
insert into target_subtype values (19,'Election-related',2);
insert into target_subtype values (20,'Intelligence',2);
insert into target_subtype values (21,'Government Building/Facility/Office',2);
insert into target_subtype values (22,'Police Building (headquarters, station, school)',3);
insert into target_subtype values (23,'Police Patrol (including vehicles and convoys)',3);
insert into target_subtype values (24,'Police Checkpoint',3);
insert into target_subtype values (25,'Police Security Forces/Officers',3);
insert into target_subtype values (26,'Prison/Jail',3);
insert into target_subtype values (27,'Military Barracks/Base/Headquarters/Checkpost',4);
insert into target_subtype values (28,'Military Recruiting Station/Academy',4);
insert into target_subtype values (29,'Military Unit/Patrol/Convoy',4);
insert into target_subtype values (30,'Military Weaponry',4);
insert into target_subtype values (31,'Military Aircraft',4);
insert into target_subtype values (32,'Military Maritime',4);
insert into target_subtype values (33,'Non-combatant Personnel',4);
insert into target_subtype values (34,'Military Personnel (soldiers, troops, officers, forces)',4);
insert into target_subtype values (35,'Military Transportation/Vehicle (excluding convoys)',4);
insert into target_subtype values (36,'Military Checkpoint',4);
insert into target_subtype values (37,'NATO',4);
insert into target_subtype values (39,'Paramilitary',4);
insert into target_subtype values (40,'Clinics',5);
insert into target_subtype values (41,'Personnel',5);
insert into target_subtype values (42,'Aircraft (not at an airport)',6);
insert into target_subtype values (43,'Airline Officer/Personnel',6);
insert into target_subtype values (44,'Airport',6);
insert into target_subtype values (45,'Diplomatic Personnel (outside of embassy, consulate)',7);
insert into target_subtype values (46,'Embassy/Consulate',7);
insert into target_subtype values (47,'International Organization (peacekeeper, aid agency, compound)',7);
insert into target_subtype values (48,'Teacher/Professor/Instructor',8);
insert into target_subtype values (49,'School/University/Educational Building',8);
insert into target_subtype values (50,'Other Personnel',8);
insert into target_subtype values (51,'Food Supply',9);
insert into target_subtype values (52,'Water Supply',9);
insert into target_subtype values (53,'Newspaper Journalist/Staff/Facility',10);
insert into target_subtype values (54,'Radio Journalist/Staff/Facility',10);
insert into target_subtype values (55,'Television Journalist/Staff/Facility',10);
insert into target_subtype values (56,'Other (including online news agencies)',10);
insert into target_subtype values (57,'Civilian Maritime',11);
insert into target_subtype values (58,'Commercial Maritime',11);
insert into target_subtype values (59,'Oil Tanker',11);
insert into target_subtype values (60,'Port',11);
insert into target_subtype values (61,'Domestic NGO',12);
insert into target_subtype values (62,'International NGO',12);
insert into target_subtype values (63,'Ambulance',13);
insert into target_subtype values (64,'Fire Fighter/Truck',13);
insert into target_subtype values (65,'Refugee (including Camps/IDP/Asylum Seekers)',14);
insert into target_subtype values (66,'Demilitarized Zone (including Green Zone)',13);
insert into target_subtype values (67,'Unnamed Civilian/Unspecified',14);
insert into target_subtype values (68,'Named Civilian',14);
insert into target_subtype values (69,'Religion Identified',14);
insert into target_subtype values (70,'Student',14);
insert into target_subtype values (71,'Race/Ethnicity Identified',14);
insert into target_subtype values (72,'Farmer',14);
insert into target_subtype values (73,'Vehicles/Transportation',14);
insert into target_subtype values (74,'Marketplace/Plaza/Square',14);
insert into target_subtype values (75,'Village/City/Town/Suburb',14);
insert into target_subtype values (76,'House/Apartment/Residence',14);
insert into target_subtype values (77,'Laborer (General)/Occupation Identified',14);
insert into target_subtype values (78,'Procession/Gathering (funeral, wedding, birthday, religious)',14);
insert into target_subtype values (79,'Public Area (garden, parking lot, garage, beach, public building, camp)',14);
insert into target_subtype values (80,'Memorial/Cemetery/Monument',14);
insert into target_subtype values (81,'Museum/Cultural Center/Cultural House',14);
insert into target_subtype values (82,'Labor Union Related',14);
insert into target_subtype values (83,'Protester',14);
insert into target_subtype values (84,'Political Party Member/Rally',14);
insert into target_subtype values (85,'Religious Figure',15);
insert into target_subtype values (86,'Place of Worship',15);
insert into target_subtype values (87,'Affiliated Institution',15);
insert into target_subtype values (88,'Radio',16);
insert into target_subtype values (89,'Television',16);
insert into target_subtype values (90,'Telephone/Telegraph',16);
insert into target_subtype values (91,'Internet Infrastructure',16);
insert into target_subtype values (92,'Multiple Telecommunication Targets',16);
insert into target_subtype values (93,'Terrorist',17);
insert into target_subtype values (94,'Non-State Militia',17);
insert into target_subtype values (95,');Tourism Travel Agency',18);
insert into target_subtype values (96,'Tour Bus/Van',18);
insert into target_subtype values (97,'Tourist',18);
insert into target_subtype values (98,'Other Facility',18);
insert into target_subtype values (99,'Bus (excluding tourists)',19);
insert into target_subtype values (100,'Train/Train Tracks/Trolley',19);
insert into target_subtype values (101,'Bus Station/Stop',19);
insert into target_subtype values (102,'Subway',19);
insert into target_subtype values (103,'Bridge/Car Tunnel',19);
insert into target_subtype values (104,'Highway/Road/Toll/Traffic Signal',19);
insert into target_subtype values (105,'Taxi/Rickshaw',19);
insert into target_subtype values (106,'Gas',21);
insert into target_subtype values (107,'Electricity',21);
insert into target_subtype values (108,'Oil',21);
insert into target_subtype values (109,'Party Official/Candidate/Other Personnel',22);
insert into target_subtype values (110,'Party Office/Facility',22);
insert into target_subtype values (111,'Rally',22);
insert into target_subtype values (112,'Legal Services',1);
insert into target_subtype values (113,'Alleged Informant',14);

