insert into weapon_subtype values(1,'Poisoning',2);
insert into weapon_subtype values(2,'Automatic or Semi-Automatic Rifle',5);
insert into weapon_subtype values(3,'Handgun',5);
insert into weapon_subtype values(4,'Rifle/Shotgun (non-automatic)',5);
insert into weapon_subtype values(5,'Unknown Gun Type',5);
insert into weapon_subtype values(6,'Other Gun Type',5);
insert into weapon_subtype values(7,'Grenade',6);
insert into weapon_subtype values(8,'Landmine',6);
insert into weapon_subtype values(9,'Letter Bomb',6);
insert into weapon_subtype values(10,'Pressure Trigger',6);
insert into weapon_subtype values(11,'Projectile (rockets, mortars, RPGs, etc.)',6);
insert into weapon_subtype values(12,'Remote Trigger',6);
insert into weapon_subtype values(13,'Suicide (carried bodily by human being)',6);
insert into weapon_subtype values(14,'Time Fuse',6);
insert into weapon_subtype values(15,'Vehicle',6);
insert into weapon_subtype values(16,'Unknown Explosive Type',6);
insert into weapon_subtype values(17,'Other Explosive Type',6);
insert into weapon_subtype values(18,'Arson/Fire',8);
insert into weapon_subtype values(19,'Molotov Cocktail/Petrol Bomb',8);
insert into weapon_subtype values(20,'Gasoline or Alcohol',8);
insert into weapon_subtype values(21,'Blunt Object',9);
insert into weapon_subtype values(22,'Hands, Feet, Fists',9);
insert into weapon_subtype values(23,'Knife or Other Sharp Object',9);
insert into weapon_subtype values(24,'Rope or Other Strangling Device',9);
insert into weapon_subtype values(26,'Suffocation',9);
insert into weapon_subtype values(27,'Unknown Weapon Type',9);
insert into weapon_subtype values(28,'Dynamite/TNT',6);
insert into weapon_subtype values(29,'Sticky Bomb',6);
insert into weapon_subtype values(30,'Explosive',2);
insert into weapon_subtype values(31,'Pipe Bomb',6);

